language: node_js
services:
- docker
before_install:
- docker-compose -f docker-compose.test.yml -p ci build   
script:
- docker-compose -f docker-compose.test.yml -p ci up -d
after_script:
- docker logs -f ci_sut