version: "3.7"

services:
    # Note.js application
    api:
        build: 
            context: "api"
            dockerfile: Dockerfile

        volumes: 
            - ./api/src/:/usr/src/api/src/
            - ./api/dist/:/usr/src/api/dist/
            - ./api/nodemon.json:/usr/src/api/nodemon.json
            - ./api/tsconfig.json:/usr/src/api/tsconfig.json
            - ./api/backend-db.sqlite:/usr/src/api/backend-db.sqlite

        expose:
            - "8080"

        ports:
            - "8080:8080"
            - "9229:9229"

        command: "npm run dev"