version: "3"
services:

    # Note.js application
    api:
        build: "api"
        ports:
            - "8080:8080"
        volumes: 
            - "./api/src:/usr/src/api"
            - "/usr/src/api/node_modules/"