version: "3.7"

services:
    # Postgres
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: test
            POSTGRES_DB: backend
        ports:
        - "35432:5432"
            
    # Node.js application
    api:
        build: 
            context: "api"
            dockerfile: Dockerfile

        environment:
            POSTGRES_URL: postgres://root:test@postgres:5432/backend

        depends_on:
            - postgres

        volumes: 
            - ./api/src/:/usr/src/api/src/
            - ./api/dist/:/usr/src/api/dist/
            - ./api/nodemon.json:/usr/src/api/nodemon.json
            - ./api/tsconfig.json:/usr/src/api/tsconfig.json
            - ./api/backend-db.sqlite:/usr/src/api/backend-db.sqlite

        expose:
            - "8080"

        ports:
            - "8080:8080"
            - "9229:9229"

        command: "npm run dev"